from .empleado_dao import EmpleadoDAO
from .equipos_dao import EquiposDAO
from .lote_production_dao import ProductionloteDAO
from .reportesEmp_dao import ReportsEmpDAO
from .reporteVul_dao import ReportVulDAO
from .solicitudes_servicio_dao import SolicitudesServicioDAO
from .transporte_dao import TransportDAO
from .user_dao import UserDAO
from .vulcanizadora_dao import VulcanizadoraDAO