name: Mi Config Local
version: 1.0.0
schema: v1

models:
  - name: Qwen 2.5 Coder 3B
    provider: ollama
    model: qwen2.5-coder:3b
    apiBase: http://127.0.0.1:11434
    roles:
      - chat
      - edit
      - apply

  - name: Qwen 2.5 Coder 1.5B
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://127.0.0.1:11434
    roles:
      - autocomplete